/**
 * Códigos estables para n8n / clientes.
 * No reescribir sin versionar: el bot ramifica por `code`, no por `message`.
 */
export const ApiErrorCode = {
  // Genéricos
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',

  // Conductor / identidad (n8n)
  DRIVER_NOT_FOUND: 'DRIVER_NOT_FOUND',
  DRIVER_INACTIVE: 'DRIVER_INACTIVE',
  DRIVER_IDENTITY_MISMATCH: 'DRIVER_IDENTITY_MISMATCH',
  DRIVER_DOCUMENT_PHONE_REQUIRED: 'DRIVER_DOCUMENT_PHONE_REQUIRED',

  // Gastos
  EXPENSE_NOT_FOUND: 'EXPENSE_NOT_FOUND',
  EXPENSE_CREATE_FAILED: 'EXPENSE_CREATE_FAILED',
  EXPENSE_DUPLICATE: 'EXPENSE_DUPLICATE',
  EXPENSE_FORBIDDEN: 'EXPENSE_FORBIDDEN',

  // Auth / panel
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  DRIVER_PROFILE_MISSING: 'DRIVER_PROFILE_MISSING',

  // Drivers admin
  DRIVER_DOCUMENT_EXISTS: 'DRIVER_DOCUMENT_EXISTS',
  DRIVER_PHONE_EXISTS: 'DRIVER_PHONE_EXISTS',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
